
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab3(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

`include "verilog/params.vh"


//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [1:0] current_state;
wire [1:0] next_state;
wire state_clock; 

wire reset;
wire hazard;
wire turn;

assign reset = ~KEY[0];
assign hazard = SW[0];
assign turn = SW[1];
assign left = KEY[1];

div10M_5 divider(ADC_CLK_10, ~reset, state_clock);

next_state_logic nextStateLogic(reset, turn, hazard, next_state);

assign LEDR[1:0] = next_state;
assign LEDR[2] = state_clock;

//=======================================================
//  Structural coding
//=======================================================
initial begin
	current_state = IDLE;
end

always @(posedge state_clock) begin
	current_state = next_state;
end

endmodule
